### ISSUE TITLE
using key

### ISSUE THREAD

**Issue by zdavatz** [ShaunHoyes/Bitfinex-account-monitor#1]
Hi

I just tried to use your library as follows:
```
~/.software/Bitfinex-account-monitor> node balances.js 
```
but this results in the following error:
```
module.js:442
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zeno/.software/Bitfinex-account-monitor/balances.js:2:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by jshoyes** [comment]
You may or may not have the `request` module installed correctly. Go to your home directory and run `npm install request`. Try running `balance.js` again and see if it works. 

Are you using Mac/Linux or Windows?

**Comment by zdavatz** [comment]
Linux!

**Comment by zdavatz** [comment]
At the moment I am using 
```
node active-credits.js
```
but I would also like to get the other side:  the Right column (Available but not lent). Is that possible?

As in:

http://docs.bitfinex.com/v1/reference#rest-auth-balance-history

**Comment by jshoyes** [comment]
@zdavatz `node active-credits.js` will give you a run-down of all of your active loans (as the lender). If you want to get a calculation of your available margin-lending funds that haven't been lent out yet (Available but not lent), run ` node available-margin-funds.js`. 

Keep in mind that `available-margin-funds.js` does not include pending loan offers.

 I will work on combining all of this info soon.

**Comment by zdavatz** [comment]
No, what I mean is an export of the historical data, based on the last minute of the day.

http://docs.bitfinex.com/v1/reference#rest-auth-balance-history

```
node available-margin-funds.js
```
does not give me a lot of useful output:
Bitfinex Funds Available for Use:
USD: $0.0
BTC: 0 satoshi

**Comment by zdavatz** [comment]
![bildschirmfoto 2017-03-05 um 21 31 59](https://cloud.githubusercontent.com/assets/4953/23591075/3f4a0082-01eb-11e7-9b19-21be75890494.png)
I mean the right column of the funding wallet.

**Comment by zdavatz** [comment]
for each of wallets USD, BFX, BTC, the historical end-of-day balances in each of the wallets Trading, Exchange, Deposit, for each of the days of that month.                        
So in my case nine balances in total, three wallets for each currency, for each end-of-day, for the 28 days in February.

**Comment by zdavatz** [comment]
Probably the best solution to keep track over the value the account over time would be to create a daily snapshot the balances and a snapshot of the ticker prices at the same time you make a snapshot and calculate the USD equivalent balance based on those tickers. This could be automated by running a API script every day (or every hour) that would make an API call to /pubticker for all pairs and to /balances API endpoints and record these numbers in a csv file for instance. http://docs.bitfinex.com/v1/reference#rest-public-ticker and http://docs.bitfinex.com/v1/reference#rest-auth-wallet-balances

**Comment by jshoyes** [comment]
@zdavatz Right now I'm focusing on giving a snapshot of the account; not so much interested in exporting historical data. I think it's overkill to be running an automated script for this. Although using historical transactional data for tax reporting purposes is on my horizon.

There's a lot of currencies being offered on Bitfinex, but at this time I'm mainly interested in USD, BTC, and quite possibly XMR.

**Comment by zdavatz** [comment]
@ShaunHoyes ok. Exactly, for Tax reasons it is very important.
